authentication/urls.py
from django.urls import path

from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.registerPage, name="registerPage"),
    path('login/', views.loginPage, name="loginPage"),
    path('logout', views.logoutPage, name='logoutPage')
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('more/', views.more, name='more')
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story1/', include('story1.urls')),
    path('search/', include('search.urls')),
    path('authentication/', include('authentication.urls'))
]

search/urls.py
from django.urls import path

from . import views

app_name = 'search'

urlpatterns = [
    path('', views.index, name='index'),
    path('api/books/<str:book>/', views.retrieve, name='retrieve')
    
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class DataProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name = models.CharField(max_length=300)
    photo = models.CharField(max_length=500)
    birthDate = models.DateField()
    city = models.CharField(max_length=50)
    def __str__(self):
        return self.name

home/models.py
from django.db import models

# Create your models here.

search/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import DataProfile
# Create your views here.

@login_required(login_url='authentication:loginPage')
def index(request):
    user = request.user
    try:
        dataProfile = DataProfile.objects.get(user=user)
        context = {
            'user': user,
            'dataProfile': dataProfile
        }
        return render(request, 'authentication/index.html', context)
    except:
        context = {
            'user': user,
        }
        return render(request, 'authentication/index.html', context)

def registerPage(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get("username")
            messages.success(request, "Your account created successfully, please login")
            return redirect('authentication:loginPage')
    context = {'form':form}
    return render(request, 'authentication/register.html', context)

def loginPage(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('authentication:index')
        else:
            messages.info(request, 'Username or password is incorrect')
    context = {}
    return render(request, 'authentication/login.html', context)

def logoutPage(request):
    logout(request)
    messages.success(request, "Logout successfully")
    return redirect('authentication:loginPage')

home/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'home/index.html')
def more(request):
    return render(request, 'home/more.html')

search/views.py
from django.shortcuts import render
import requests
from django.http import HttpResponse
import json

# Create your views here.

def index(request):
    return render(request, 'search/index.html')

def retrieve(request, book):
    req = requests.get("https://www.googleapis.com/books/v1/volumes?q=" + book)
    data = req.json()
    data = json.dumps(data)
    print(data)
    return HttpResponse(content = data, content_type="application/json")

story1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story1/index.html')

authentication/templates/authentication/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> {% block css %} {% endblock css %}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    {% block content%} {% endblock content%} {% block js %} {% endblock js %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

authentication/templates/authentication/index.html
{% extends 'authentication/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'authentication/style.css' %}"> {% endblock css %} {% block title %}Home{% endblock title %} {% block content %}
<div class="wrapper d-flex flex-column justify-content-center align-items-center">
    <div class="box d-flex flex-column justify-content-center align-items-center">
        {% if dataProfile %}
        <img src="{{ dataProfile.photo }}" alt="" width="100" height="100" class="mb-3">
        <h3>{{ dataProfile.name }}</h3>
        <h5>{{ dataProfile.city }}, {{ dataProfile.birthDate }}</h5>
        {% else %}
        <h3 style="color: aliceblue !important;">Hello, {{ request.user }}</h3>
        {% endif %}
        <p class="m-0" style="color: aliceblue !important;">Thankyou for login to my page</p>
    </div>
    <a href="{% url 'authentication:logoutPage' %}">
        <button type="button" class="btn btn-light btn-logout">Logout</button>
    </a>
</div>
{% endblock content %}

authentication/templates/authentication/login.html
{% extends 'authentication/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'authentication/register.css' %}"> {% endblock css %} {% block title %}Login{% endblock title %} {% block content %} {% if user.is_authenticated %}
<div class="wrapper d-flex flex-column align-items-center justify-content-center">
    <div class="box d-flex flex-column justify-content-center align-items-center">
        <h4 class="title">You've logged in</h4>
        <a href="{% url 'authentication:index' %}">
            <button type="submit" class="btn btn-light btn-auth align-self-center">Back to Home</button>
        </a>
    </div>
</div>
{% else %}
<div class="wrapper bg-dark d-flex flex-column align-items-center justify-content-center">
    <div class="box d-flex flex-column justify-content-center align-items-center">
        <h4 class="title" style="color: aliceblue;">Selamat Datang!</h4>
        <form action="" method="post" class="d-flex flex-column justify-content-center">
            {% csrf_token %}
            <div class="form-group">
                <label style="color: aliceblue;" for="username">Username</label>
                <input type="text" class="form-control" name="username" autocomplete="username">
            </div>
            <div class="form-group">
                <label style="color: aliceblue;" for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" name="password" autocomplete="current-password">
            </div>
            {% for message in messages %} {% if message.tags == 'info' %}
            <small class="form-text text-danger form-error mt-0 mb-3">{{ message }}</small> {% endif %} {% if message.tags == 'success' %}
            <small class="form-text text-success form-error mt-0 mb-3">{{ message }}</small> {% endif %} {% endfor %}
            <button type="submit" class="btn btn-light btn-auth align-self-center">Login</button>
            <p style="color: aliceblue !important;">Belum punya akun? Yuk daftar! <a href="{% url 'authentication:registerPage' %}">Sign Up</a></p>
        </form>
    </div>
</div>
{% endif %} {% endblock content %} {% block js %}
<script>
    $("input").addClass("form-control")
    $("input").eq(1).attr("placeholder", 'Masukan username Anda')
    $("input").eq(2).attr("placeholder", 'Masukan password Anda')
</script>
{% endblock js %}

authentication/templates/authentication/register.html
{% extends 'authentication/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'authentication/register.css' %}"> {% endblock css %} {% block title %}Register{% endblock title %} {% block content %} {% if user.is_authenticated %}
<div class="wrapper d-flex flex-column align-items-center justify-content-center">
    <div class="box d-flex flex-column justify-content-center align-items-center">
        <h4 class="title">You've logged in</h4>
        <a href="{% url 'authentication:index' %}">
            <button type="submit" class="btn btn-light btn-auth align-self-center">Back to Home</button>
        </a>
    </div>
</div>
{% else %}
<div class="wrapper d-flex flex-column align-items-center justify-content-center">
    <div class="box d-flex flex-column justify-content-center align-items-center">
        <h4 class="title">Register</h4>
        <form action="" method="post" class="d-flex flex-column justify-content-center">
            {% csrf_token %}
            <div class="form-group">
                <label style="color: aliceblue !important;" for="exampleInputEmail1">Username</label> {{form.username}}
                <small class="form-text text-danger form-error">{{ form.errors.username }}</small>
            </div>
            <div class="form-group">
                <label style="color: aliceblue !important;" for="exampleInputPassword1">Password</label> {{form.password1}}
                <small class="form-text text-danger form-error">{{ form.errors.password1 }}</small>
            </div>
            <div class="form-group">
                <label style="color: aliceblue !important;" for="exampleInputPassword2">Confirm Your Password</label> {{form.password2}}
                <small class="form-text text-danger form-error">{{ form.errors.password2 }}</small>
            </div>
            <button style="color: aliceblue !important;" type="submit" class="btn btn-light btn-auth align-self-center">Register</button>
            <p style="color: aliceblue !important;">Already have an account? <a href="{% url 'authentication:loginPage' %}">Sign In</a></p>
        </form>
    </div>
</div>
{% endif %} {% endblock content %} {% block js %}
<script>
    $("input").addClass("form-control");
    $("input").eq(1).attr("placeholder", 'Username...');
    $("input").eq(2).attr("placeholder", 'Enter Password...');
    $("input").eq(3).attr("placeholder", 'Re-Enter Password...');
</script>
{% endblock js %}

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <title>Story 4</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-light navbar-expand-lg fixed-top px-5 pt-3">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto d-flex align-items-end">
                    <a class="nav-item nav-link" href="{% url 'home:index' %}#about"> ABOUT</a>
                    <a class="nav-item nav-link" href="{% url 'home:index' %}#hobbies"> HOBBIES</a>
                    <a class="nav-item nav-link" href="{% url 'home:index' %}#experiences"> EXPERIENCES</a>
                    <a class="nav-item nav-link" href="{% url 'home:index' %}#contact"> CONTACT</a>
                    <a class="nav-item nav-link" href="{% url 'story1:index' %}"> STORY 1</a>
                    <a class="nav-item nav-link nav-bonus" href="{% url 'home:more' %}">MORE</a>
                </div>
            </div>
        </nav>
        <div class="imageku">
            <img src="{% static 'home/images/IbnuBulet.svg' %}" alt="ibnuganteng">
        </div>
        <div class="header-text-a d-flex justify-content-end">
            <h3 class="title" data-aos="fade-right">WELCOME</h3>
        </div>
        <div class="header-text-b d-flex justify-content-end">
            <h5 data-aos="fade-left">Mari mengenal Ibnu lebih dekat disini!</h5>
        </div>
        <div class="namaIbnu">
            <img src="{% static 'home/images/IBNU.svg' %}" alt="Ibnu Hambali">
        </div>
    </header>
    {% block section %} {% endblock %}
    <footer class="d-flex flex-md-row justify-content-between align-items-center" id="contact">
        <h3>Let's connect<br>with me</h3>
        <div class="footer-icon-group d-flex justify-content-between align-items-center">
            <a href="https://gitlab.com/hambaliibnu27"><img src="{% static 'home/images/Vector.svg' %}" alt=""></a>
            <a href="https://www.linkedin.com/in/ibnuhambali/"><img src="{% static 'home/images/linkedin.svg' %}" alt="" srcset=""></a>
            <a href="https://instagram.com/itenkoui"><img src="{% static 'home/images/instagram.svg' %}" alt=""></a>
            <a href="mailto:hambaliibnu27@gmail.com"><img src="{% static 'home/images/gmail.svg' %}" alt="" srcset=""></a>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>

</html>

home/templates/home/index.html
{% extends 'home/base.html' %} {% load static %} {% block navbar %} {% include 'home/base.html' %} {% endblock %} {% block section %}
<section class="about d-flex flex-column justify-content-around" id="about">
    <div class="about-text" data-aos="fade-right">
        <h1 class="about-text-left">Saya adalah orang yang haus akan ilmu-ilmu dunia yang beragam. Saya senang mempelajari segala hal baru yang saya rasa menarik untuk ditelusuri, sekalipun hal tersebut dianggap tabu oleh sebagian orang di Indonesia.</h1>
    </div>
    <div class="about-text" data-aos="fade-left">
        <h3 class="about-text-right">Senang tampil berbeda adalah kebiasaan saya, karena menurut saya manusia adalah makhluk yang unik, yang masing-masing memang berbeda, dan saya senang mempertahankan perbedaan itu, dan tidak berusaha menjadi sama seperti orang lain.</h3>
    </div>
</section>
<section class="hobbies" id="hobbies">
    <h3>MY HOBBIES</h3>
    <div class="hobbies-icon-group d-flex justify-content-around" id="hobby-box">
        <a data-aos="fade-right" href="http://www.arabiccalligraphy.com/#!/home"><img src="{% static 'home/images/GambarFix.svg' %}" alt=""></a>
        <a data-aos="fade-down" href="https://www.youtube.com/user/AsapSCIENCE"><img src="{% static 'home/images/nontonyt.svg' %}" alt="" srcset=""></a>
        <a data-aos="fade-left" href="https://www.duolingo.com/"><img src="{% static 'home/images/Gtrans.svg' %}" alt=""></a>
    </div>
</section>
<section class="experiences" id="experiences">
    <h3>MY EXPERIENCES</h3>
    <div class="experiences-icon-group1 d-flex flex-md-row justify-content-between align-items-center">
        <a data-aos="flip-left" href="https://bem.cs.ui.ac.id/"><img src="{% static 'home/images/BEM.svg' %}" alt=""></a>
        <a data-aos="flip-right" href="https://pmb.cs.ui.ac.id/"><img src="{% static 'home/images/PMB.svg' %}" alt=""></a>
    </div>
    <div class="experiences-icon-group2 d-flex flex-md-row justify-content-between align-items-center">
        <a data-aos="flip-left" href="https://compfest.id"><img src="{% static 'home/images/Compfest.svg' %}" alt="" srcset=""></a>
        <a data-aos="flip-right" href="http://uiyea.org/"><img src="{% static 'home/images/UIYEA.svg' %}" alt=""></a>
    </div>
</section>
{% endblock %}

home/templates/home/more.html
{% extends 'home/base.html' %} {% load static %} {% block navbar %} {% include 'home/base.html' %} {% endblock %} {% block section %}
<section class="more" id="more">
    <h3>RIWAYAT PENDIDIKAN</h3>
    <div class="more d-flex flex-md-row justify-content-between align-items-center">
        <h4 data-aos="fade-left">SD</h4>
        <h4 data-aos="fade-left">SDN SEMANAN 01 PAGI</h4>
    </div>
    <div class="more d-flex flex-md-row justify-content-between align-items-center">
        <h4 data-aos="fade-left">SMP</h4>
        <h4 data-aos="fade-left">MTsN 8 JAKARTA</h4>
    </div>
    <div class="more d-flex flex-md-row justify-content-between align-items-center">
        <h4 data-aos="fade-left">SMA</h4>
        <h4 data-aos="fade-left">SMAN 94 JAKARTA</h4>
    </div>
    <div class="more d-flex flex-md-row justify-content-between align-items-center">
        <h4 data-aos="fade-left">PERGURUAN TINGGI</h4>
        <h4 data-aos="fade-left">FASILKOM UNIVERSITAS INDONESIA</h4>
    </div>
</section>
{% endblock %}

search/templates/search/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Story 8</title>
</head>

<body style="background-color: yellow; margin-left: 50px; margin-right: 50px; text-align: center;">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    <h1>ITenkoUI Search Books</h1>
    <input id="keyword" placeholder="Cari apa?...">

    <table id="hasil" border="1">

        <!-- ajax -->

    </table>

    <script src="{% static 'search/main.js' %}"></script>

</body>

</html>

story1/templates/story1/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Belajar PPW</title>
    <style>
        h1 {
            color: blueviolet;
            text-align: center;
            margin-top: 50px;
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        }
        
        .gambar {
            text-align: center;
        }
        
        h2 {
            color: rgb(8, 0, 128);
            text-align: center;
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        }
        
        li {
            color: rgb(0, 0, 0);
            text-align: justify;
            margin-left: 120px;
            margin-right: 130px;
        }
        
        li li {
            color: rgb(0, 0, 0);
            text-align: justify;
            margin-left: 120px;
            margin-right: 130px;
        }
    </style>
</head>

<body>
    <h1>Selamat Datang di Web ITENKOUI</h1>
    <div class="gambar">
        <img src="{% static 'story1/images/Ibnu.JPG' %}" alt="" width="200">
    </div>

    <h2>Ibnu Hambali - 1906353403</h2>
    <h2>MAUNG 2019</h2>
    <ul>
        <li><b>Hobi</b>
            <ul>
                <li>Mencari kebenaran</li>
                <li>Menonton youtube</li>
                <li>Belajar bahasa asing (nice to know) : Ibrani, Jepang, Arab, Turki, Belanda</li>
                <li>Menggambar</li>
            </ul>
        </li>
        <li><b>Deskripsi</b>
            <ul>
                <p>Saya adalah orang yang haus akan ilmu-ilmu dunia yang beragam. Saya senang mempelajari segala hal baru yang saya rasa menarik untuk ditelusuri, sekalipun hal tersebut dianggap tabu oleh sebagian orang di Indonesia. Senang tampil berbeda
                    adalah kebiasaan saya, karena menurut saya manusia adalah makhluk yang unik, yang masing-masing memang berbeda, dan saya senang mempertahankan perbedaan itu, dan tidak berusaha menjadi sama seperti orang lain.
                </p>
            </ul>
        </li>
        <li><b>Riwayat Pendidikan</b>
            <ul>
                <li>SD Negeri Semanan 01 Pagi : 2006 - 2012</li>
                <li>MTs Negeri 8 Jakarta : 2012 - 2015</li>
                <li>SMA Negeri 94 Jakarta : 2015 - 2018</li>
                <li>Fakultas Kedokteran UPN "Veteran" Jakarta : 2018 - 2019</li>
                <li>Fasilkom Universitas Indonesia : 2019 - Sekarang</li>
            </ul>
        </li>
        <li><b>Media Sosial</b>
            <ul>
                <li>Instagram : <a href="https://www.instagram.com/itenkoui/">@itenkoui</a></li>
                <li>line : itenkoino1</li>
                <li>linkedin : <a href="https://www.linkedin.com/in/ibnuhambali/">Ibnu Hambali</a></li>
            </ul>
        </li>
    </ul>





</body>

</html>